# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4760ce789d5bc64b5f373fb33e2aaca8d7e67a1a181513495cf461a6064103629549be991c45e2519d153ad9c4802e2bb76762a5315bcae2993113bcbfb280a6

test:
  secret_key_base: db334a6924ee460bcb4fa0a05f4075a36c3f5ac7dbc7e604212bb7494f581f37e94b97f5f5a083c3ea85f87d4fc167490407de67f7498ac5ae16333784e322ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
